# Generated by Django 2.2 on 2020-05-14 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('folder', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('size', models.CharField(blank=True, max_length=10, null=True)),
                ('extension', models.CharField(max_length=10)),
                ('thumb', models.CharField(max_length=200, null=True)),
                ('download_url', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_file_folder', to='folder.FolderHierarchy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_file_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
