# Generated by Django 2.2 on 2020-05-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='download_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='extension',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='thumb',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
